apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: krakend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - hosts:
        - krakend.blinddateg3.xyz
      secretName: blinddateg3-krakend-tls
  rules:
  - host: krakend.blinddateg3.xyz
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: krakend-service
            port:
              number: 8000

