apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - post-service-deployment.yaml
  - comment-service-deployment.yaml
  - user-service-deployment.yaml
  - krakend-deployment.yaml
  - api-gateway-ingress.yaml
  - cluster-issuer.yaml
  - secrets.yaml



images:
  - name: g3Registry.azurecr.io/post-service
    newName: g3Registry.azurecr.io/post-service
    newTag: CICD_PLACEHOLDER
  - name: g3Registry.azurecr.io/comment-service
    newName: g3Registry.azurecr.io/comment-service
    newTag: CICD_PLACEHOLDER
  - name: g3Registry.azurecr.io/user-service
    newName: g3Registry.azurecr.io/user-service
    newTag: CICD_PLACEHOLDER
  - name: g3Registry.azurecr.io/krakend
    newName: g3Registry.azurecr.io/krakend
    newTag: CICD_PLACEHOLDER
